[tools]
uv = "latest"
# =================================================================================================
# CI Tools
# =================================================================================================
actionlint = "latest"
yamllint = "latest"