---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create Release

on:
  workflow_call:
    inputs:
      project-directory:
        required: true
        type: string
      project-name:
        required: true
        type: string
    outputs:
      version:
        description: The version of the release (without prefix)
        value: ${{ jobs.create-release.outputs.version }}

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version_step.outputs.semVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@baa11fbfe1d6520db94683bd5c7a3818018e4309 # v5.1.0
        with:
          global-json-file: global.json

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@71a79f7569b981036febd9ce5870f87e069928e7 # v4.3.3
        with:
          versionSpec: "6.4.x"
          preferLatestVersion: true

      - name: Determine Version
        id: version_step
        uses: gittools/actions/gitversion/execute@71a79f7569b981036febd9ce5870f87e069928e7 # v4.3.3
        with:
          configFilePath: "${{ inputs.project-directory }}/GitVersion.yaml"

      - name: Generate Changelog
        run: |
          PREVIOUS_TAG=$(git tag -l "${{ inputs.project-name }}-*" --sort=-version:refname | head -n 1)

          {
            echo "## What's Changed"
            echo ""

            echo "### Features"
            echo ""

            git log "${PREVIOUS_TAG}".. --grep="^feat" --pretty=format:"- %s by @%an" ${{ inputs.project-directory }}
            echo ""

            echo "### Bugfixes"
            echo ""

            git log "${PREVIOUS_TAG}".. --grep="^fix" --pretty=format:"- %s by @%an" ${{ inputs.project-directory }}
            echo ""

            echo "### Dependency Updates"
            echo ""

            git log "${PREVIOUS_TAG}".. --grep="^chore" --pretty=format:"- %s by @%an" ${{ inputs.project-directory }}
            echo ""
          } >> CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@b7eabc95ff50cbeeedec83973935c8f306dfcd0b # v1.20.0
        with:
          tag: ${{ inputs.project-name }}-${{ steps.version_step.outputs.semVer }}
          name: ${{ inputs.project-name }} ${{ steps.version_step.outputs.semVer }}
          bodyFile: CHANGELOG.md
